# Default values for service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: <ECR-repository>
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: <Certificate-ARN>

service:
  type: NodePort
  port: 443
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <SSL-certificate-ARN>
  env:
    port: 3000



resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
